### Filter Price Data for the four days and save

In [2]:
import pandas as pd

# Read the CSV file
df = pd.read_csv("../data/homework3bus.csv")

# Display the dataframe
df

,Unnamed: 0,l_P,l_Q,s_max,c,v_min,v_max,r,x,I_max
0,0,0.000,0.000,5.0,100.0,0.95,1.05,"[0, 0.007547918, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0.022173236, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 3.0441, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
1,1,0.200,0.116,0.0,0.0,0.95,1.05,"[0, 0, 0.0041, 0, 0.007239685, 0, 0.007547918,...","[0, 0, 0.0064, 0, 0.007336076, 0, 0.022173236,...","[0, 0, 1.4178, 0, 0.9591, 0, 3.0441, 0, 0, 0, ..."
2,2,0.000,0.000,0.0,0.0,0.95,1.05,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 3.1275, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
3,3,0.400,0.290,3.0,150.0,0.95,1.05,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
4,4,0.170,0.125,0.0,0.0,0.95,1.05,"[0, 0, 0, 0, 0, 0.004343811, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0.004401645, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0.9591, 0, 0, 0, 0, 0, 0, 0]"
5,5,0.230,0.132,0.0,0.0,0.95,1.05,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
6,6,1.155,0.660,0.0,0.0,0.95,1.05,"[0, 0, 0, 0, 0, 0, 0, 0.003773959, 0, 0, 0.004...","[0, 0, 0, 0, 0, 0, 0, 0.011086618, 0, 0, 0.004...","[0, 0, 0, 0, 0, 0, 0, 3.0441, 3.1275, 0, 0.959..."
7,7,0.000,0.000,0.0,0.0,0.95,1.05,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
8,8,0.170,0.151,0.0,0.0,0.95,1.05,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0.00434686, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0.002430473, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1.37193, 0, 0, 0]"
9,9,0.843,0.462,3.0,50.0,0.95,1.05,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
10,10,0.000,0.000,0.0,0.0,0.95,1.05,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.004343157,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.004402952,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.9591, 1.2927]"
11,11,0.170,0.080,0.0,0.0,0.95,1.05,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
12,12,0.128,0.086,0.0,0.0,0.95,1.05,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"

### Create Price Dataframes for specific dates

In [11]:
price_df = pd.read_csv(f"../data/0096WD_7_N001_LMP_12months.csv")

# Sort dataframe by date times INTERVALSTARTTIME_GMT
price_df = price_df.sort_values(by="INTERVALSTARTTIME_GMT")


price_df

,INTERVALSTARTTIME_GMT,INTERVALENDTIME_GMT,OPR_DT,OPR_HR,OPR_INTERVAL,NODE_ID_XML,NODE_ID,NODE,MARKET_RUN_ID,LMP_TYPE,XML_DATA_ITEM,PNODE_RESMRID,GRP_TYPE,POS,MW,GROUP
0,2025-01-01 00:00:00+00:00,2025-01-01 01:00:00+00:00,2024-12-31,17,0,0096WD_7_N001,0096WD_7_N001,0096WD_7_N001,DAM,LMP,LMP_PRC,0096WD_7_N001,ALL,1,51.50206,1
1,2025-01-01 01:00:00+00:00,2025-01-01 02:00:00+00:00,2024-12-31,18,0,0096WD_7_N001,0096WD_7_N001,0096WD_7_N001,DAM,LMP,LMP_PRC,0096WD_7_N001,ALL,1,52.66897,1
2,2025-01-01 02:00:00+00:00,2025-01-01 03:00:00+00:00,2024-12-31,19,0,0096WD_7_N001,0096WD_7_N001,0096WD_7_N001,DAM,LMP,LMP_PRC,0096WD_7_N001,ALL,1,51.19425,1
3,2025-01-01 03:00:00+00:00,2025-01-01 04:00:00+00:00,2024-12-31,20,0,0096WD_7_N001,0096WD_7_N001,0096WD_7_N001,DAM,LMP,LMP_PRC,0096WD_7_N001,ALL,1,51.23666,1
4,2025-01-01 04:00:00+00:00,2025-01-01 05:00:00+00:00,2024-12-31,21,0,0096WD_7_N001,0096WD_7_N001,0096WD_7_N001,DAM,LMP,LMP_PRC,0096WD_7_N001,ALL,1,51.32875,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2025-12-31 19:00:00+00:00,2025-12-31 20:00:00+00:00,2025-12-31,12,0,0096WD_7_N001,0096WD_7_N001,0096WD_7_N001,DAM,LMP,LMP_PRC,0096WD_7_N001,ALL,1,44.92084,6
8756,2025-12-31 20:00:00+00:00,2025-12-31 21:00:00+00:00,2025-12-31,13,0,0096WD_7_N001,0096WD_7_N001,0096WD_7_N001,DAM,LMP,LMP_PRC,0096WD_7_N001,ALL,1,44.33853,6
8757,2025-12-31 21:00:00+00:00,2025-12-31 22:00:00+00:00,2025-12-31,14,0,0096WD_7_N001,0096WD_7_N001,0096WD_7_N001,DAM,LMP,LMP_PRC,0096WD_7_N001,ALL,1,44.30966,6
8758,2025-12-31 22:00:00+00:00,2025-12-31 23:00:00+00:00,2025-12-31,15,0,0096WD_7_N001,0096WD_7_N001,0096WD_7_N001,DAM,LMP,LMP_PRC,0096WD_7_N001,ALL,1,43.52434,6
8759,2025-12-31 23:00:00+00:00,2026-01-01 00:00:00+00:00,2025-12-31,16,0,0096WD_7_N001,0096WD_7_N001,0096WD_7_N001,DAM,LMP,LMP_PRC,0096WD_7_N001,ALL,1,43.37472,6

In [ ]:
def filter_by_day_and_save(df, date, filename):
    # Only keep the columns INTERVALSTARTTIME_GMT and MW
    df = df[["INTERVALSTARTTIME_GMT", "MW"]]

    # rename the columns from "INTERVALSTARTTIME_GMT" to "StartTime_GMT" and "MW" to "$/MW"
    df = df.rename(columns={"INTERVALSTARTTIME_GMT": "StartTime_GMT", "MW": "$/MW"})

    

    # Convert INTERVALSTARTTIME_GMT to datetime
    df["StartTime_GMT"] = pd.to_datetime(df["StartTime_GMT"])

    # Filter the dataframe for the specified date
    filtered_df = df[df["StartTime_GMT"].dt.date == pd.to_datetime(date).date()].reset_index(drop=True)
    
    display(filtered_df)
    
    # Save the filtered dataframe to a new CSV file in data folder with the specified filename
    filepath = f"../data/{filename}"
    filtered_df.to_csv(filepath, index=False)

filter_by_day_and_save(price_df, "2025-04-10", "price_df_0096WD_7_N001_2025-04-10.csv")
filter_by_day_and_save(price_df, "2025-04-10", "price_df_0096WD_7_N001_2025-04-10.csv")
filter_by_day_and_save(price_df, "2025-04-10", "price_df_0096WD_7_N001_2025-04-10.csv")
filter_by_day_and_save(price_df, "2025-04-10", "price_df_0096WD_7_N001_2025-04-10.csv")

               StartTime_GMT      $/MW
0  2025-04-10 00:00:00+00:00  18.39588
1  2025-04-10 01:00:00+00:00  48.76914
2  2025-04-10 02:00:00+00:00  54.68878
3  2025-04-10 03:00:00+00:00  50.35215
4  2025-04-10 04:00:00+00:00  48.64582
5  2025-04-10 05:00:00+00:00  46.69302
6  2025-04-10 06:00:00+00:00  43.54821
7  2025-04-10 07:00:00+00:00  40.58558
8  2025-04-10 08:00:00+00:00  40.09454
9  2025-04-10 09:00:00+00:00  36.11954
10 2025-04-10 10:00:00+00:00  34.84595
11 2025-04-10 11:00:00+00:00  36.45646
12 2025-04-10 12:00:00+00:00  41.48765
13 2025-04-10 13:00:00+00:00  49.13702
14 2025-04-10 14:00:00+00:00  33.06252
15 2025-04-10 15:00:00+00:00  -1.60682
16 2025-04-10 16:00:00+00:00  -5.95592
17 2025-04-10 17:00:00+00:00  -5.98615
18 2025-04-10 18:00:00+00:00  -6.73350
19 2025-04-10 19:00:00+00:00  -6.96041
20 2025-04-10 20:00:00+00:00  -7.67232
21 2025-04-10 21:00:00+00:00  -7.40127
22 2025-04-10 22:00:00+00:00  -4.26594
23 2025-04-10 23:00:00+00:00   2.13313